### ISSUE TITLE
update basic usage code block in readme.md with correction

### ISSUE THREAD

**Issue by ahmedh01** [Techassi/vue-youtube-iframe#1]
There a slight mistake in the basic usage code in the instructions found in the readme.

In the import statement for `main.js`, it says:

```import VueYouTubeIframe from 'vue-youtube-iframe';```

However, this will not work. It in-fact needs to explicitly mention `@techassi/`, so the import statement is going to be:

```import VueYouTubeIframe from '@techassi/vue-youtube-iframe'```

^ will work.

**Comment by Techassi** [comment]
Thanks for pointing out this small mistake. You are 100% correct.

I updated the README in the latest commit edb063c
