### ISSUE TITLE
Property was accessed during render but is not defined on instance. 

### ISSUE THREAD

**Issue by beshur** [Techassi/vue-youtube-iframe#10]
Hi.
I'm new to Vue.
Using the example code from readme the embed widget is empty and I get the following error in console:

> [Vue warn]: Property "CZqTF006RWg" was accessed during render but is not defined on instance. 

After adding app.use(YoutubeIframe), here is the view code:
```
<script setup lang="ts">
import { ref } from "vue";
const yt = ref(null);
const ready = ref(null)
</script>

<template>
  <main>
    <youtube-iframe
      ref="yt"
      :videoId="CZqTF006RWg"
      :playerWidth="600"
      :playerHeight="300"
      :noCookie="true"></youtube-iframe>
  </main>
</template>
```

Could you please help?

**Comment by Techassi** [comment]
Please use the ref in combination with the `onMounted` hook. The player is only available after being mounted.

**Comment by beshur** [comment]
Thank you for reply, will take a look.
