### ISSUE TITLE
Vue 2

### ISSUE THREAD

**Issue by strebl** [Techassi/vue-youtube-iframe#4]
Nice plugin, thanks!

Is it possible to add Vue 2 support? Nuxt is not Vue 3 compatible, I'm pretty sure there are many people stuck on Vue 2 at the moment.

**Comment by Techassi** [comment]
Hey @strebl,

thank you for your support! I currently have no plan to support Vue 2, but I will consider it for the next release.

I will look into the technical details required to make this work. Do you have any suggestions on plugins which support both Vue 2 & 3? One approach I can think of is to use `vue-demi`

**Comment by strebl** [comment]
Hi @Techassi 

Thanks for the fast response :) Yes, `vue-demi` seems to be the way to go.

https://github.com/ambit-tsai/echarts-for-vue doesn't use `vue-demi`, but I'm pretty sure thats not possible in your case, because you are using Vue 2 incompatible syntax right?

Most packages I found solved that in a different branch :( But I totally understand that you don't want to to that.

**Comment by Techassi** [comment]
Great input! Thank you for that.

As I said: I will look into it and will then decide which way is the best one to go. As of now, `vue-demi` seems like the best solution, which does not involve many changes.

**Comment by Techassi** [comment]
Vue 2 support is now available with the new package [vue-youtube](https://github.com/vue-youtube/vue-youtube). Closing.
