### ISSUE TITLE
How to start/stop the video with Javascript?

### ISSUE THREAD

**Issue by Dylan190774** [Techassi/vue-youtube-iframe#5]
Hi, I couldn't find methods like 'playVideo' and 'pauseVideo' in your component, like the ones in `vue-youtube-embed`  (which is sadly only working in Vue2).

Is there a way to start and stop the video with Javascript?

**Comment by Dylan190774** [comment]
Never mind, I found it:

```
<youtube-iframe
  ref="youtube"
  video-id="IwOfCgkyEj0"
  :no-cookie="true"
  :player-width="280"
  :player-height="200"
></youtube-iframe>

const youtube = ref(null);

youtube.value.playVideo();

```

**Comment by Techassi** [comment]
Yupp just use the `playVideo()` method
